// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AreaSelect: typeof import('./components/AreaSelect.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    PanelV1: typeof import('./components/PanelV1.vue')['default']
    PanelV2: typeof import('./components/PanelV2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }

}
