// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Angle: typeof import('./components/Angle.vue')['default']
    CardV1: typeof import('./components/CardV1.vue')['default']
    ChartRender: typeof import('./components/ChartRender.vue')['default']
    CountTo: typeof import('./components/CountTo/index.vue')['default']
    DynamicTable: typeof import('./components/DynamicTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    PanelV1: typeof import('./components/PanelV1.vue')['default']
    PanelV2: typeof import('./components/PanelV2.vue')['default']
    PanelV3: typeof import('./components/PanelV3.vue')['default']
    Popup: typeof import('./components/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
  }

}
